import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'tr' | 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  tr: {
    // Login
    'admin_panel': 'Yönetim Paneli',
    'shelter_system': 'Sığınak Yönetim Sistemi',
    'account_type': 'Hesap Türü',
    'admin': 'Admin',
    'staff': 'Staff',
    'username': 'Kullanıcı Adı',
    'password': 'Şifre',
    'login': 'Giriş Yap',
    'demo_note': 'Demo: admin/123456 veya staff/123456',
    'invalid_credentials': 'Geçersiz kullanıcı adı veya şifre',
    'email_address': 'E-Posta Adresi',
    'register': 'Kayıt Ol',

    // Dashboard
    'dashboard': 'Kontrol Paneli',
    'welcome': 'Hoş Geldiniz',
    'central_admin': 'Merkezi Yönetici',
    'shelter_staff': 'Sığınak Personeli',
    'total_people': 'Toplam Kişi',
    'total_shelters': 'Toplam Sığınak',
    'emergency_requests': 'Acil Talepler',
    'capacity_usage': 'Kapasite Kullanımı',
    'emergency_summary': 'Acil Durum Özeti',
    'shelters_status': 'Sığınak Durumu',
    'main_shelter': 'Ana Sığınak',
    'main_shelters': 'Ana Sığınaklar',
    'current_shelter': 'Bulunduğunuz Sığınak',
    'small_shelter': 'Küçük Sığınak',
    'open': 'Açık',
    'closed': 'Kapalı',
    'full': 'Dolu',
    'quick_actions': 'Hızlı İşlemler',
    'view_all_shelters': 'Tüm Sığınakları Gör',
    'emergency_alerts': 'Acil Durum Uyarıları',
    'manage_capacity': 'Kapasiteyi Yönet',
    'send_notification_btn': 'Bildirim Gönder',
    'staff_dashboard': 'Saha Operasyon Ekranı',
    'admin_dashboard': 'Bölgesel Yönetim Paneli',
    'super_admin_dashboard': 'Stratejik Komuta Merkezi',
    'seismic_heartbeat': 'Sismik Kalp Atışı',
    'live_data': 'Veriler Canlı Akıyor',
    'operational_readiness': 'Operasyonel Hazırlık',
    'team_directory': 'Personel Rehberi',
    'active_staff': 'Aktif Saha Personeli',
    'administrators': 'Yöneticiler',
    'my_team': 'Ekibim',
    'on_duty': 'Görevde',
    'on_break': 'Molada',
    'contact_admin': 'Yöneticiye Ulaş',
    'staff_performance': 'Personel Performansı',
    'earthquake_monitor': 'Canlı Deprem Takibi',
    'latest_earthquakes': 'Son Depremler',
    'magnitude': 'Büyüklük',
    'depth': 'Derinlik',
    'location_city': 'Yer / Şehir',
    'istanbul_status': 'İstanbul Durumu',
    'safe_zone_status': 'Güvenli Bölge Analizi',
    'last_activity': 'Son Hareketlilik',

    // Shelters
    'shelter_management': 'Sığınak Yönetimi',
    'manage_shelters_desc': 'Sistemdeki tüm sığınakları yönetin',
    'add_shelter': 'Yeni Sığınak',
    'add_shelter_desc': 'Yeni bir sığınak eklemek için aşağıdaki bilgileri doldurun.',
    'shelter_name': 'Sığınak Adı',
    'location': 'Konum',
    'type': 'Tür',
    'status': 'Durum',
    'capacity': 'Kapasite',
    'actions': 'İşlemler',
    'main': 'Ana',
    'small': 'Küçük',
    'linked_to': 'Bağlı',
    'address': 'Adres',
    'latitude': 'Enlem',
    'longitude': 'Boylam',

    // Capacity
    'capacity_management': 'Kapasite Yönetimi',
    'capacity_desc': 'Sığınak bölümleri ve kapasiteleri',
    'total_capacity': 'Toplam Kapasite',
    'occupied': 'Dolu',
    'available': 'Müsait',
    'usage': 'Kullanım',
    'overall_occupancy': 'Genel Doluluk Oranı',
    'auto_update_qr': 'QR tarama ile otomatik güncellenir',
    'sections': 'Bölümler',
    'families': 'Aileler',
    'individuals': 'Bireyler',
    'children': 'Çocuklar',
    'special_needs': 'Özel İhtiyaç',
    'unregistered': 'Kayıtsız',
    'current': 'Mevcut',
    'max': 'Maksimum',
    'update': 'Güncelle',

    // Emergency
    'emergency_management': 'Acil Durum Talepleri',
    'emergency_desc': 'Tüm acil durum çağrılarını yönetin',
    'all': 'Tümü',
    'new': 'Yeni',
    'in_progress': 'Devam Eden',
    'completed': 'Tamamlandı',
    'resolved': 'Çözüldü',
    'sos': 'SOS',
    'ambulance': 'Ambulans',
    'transfer': 'Transfer',
    'high_priority': 'Yüksek Öncelik',
    'high': 'Yüksek',
    'medium': 'Orta',
    'low': 'Düşük',
    'call': 'Ara',
    'navigate': 'Yol Tarifi',
    'start': 'Başlat',
    'complete': 'Tamamla',

    // QR Logs
    'qr_logs': 'QR Giriş/Çıkış Kayıtları',
    'qr_logs_desc': 'Tüm QR tarama kayıtlarını izleyin',
    'entry': 'Giriş',
    'exit': 'Çıkış',
    'net_change': 'Net Değişim',
    'total_logs': 'Toplam Kayıtlar',
    'people_count': 'Kişi',
    'time': 'Zaman',
    'user_label': 'Kullanıcı',
    'section_label': 'Bölüm',
    'qr_code_label': 'QR Kod',
    'all_shelters': 'Tüm Sığınaklar',

    // Families
    'family_management': 'Aile Yönetimi',
    'family_desc': 'Aileleri bir arada tutun',
    'total_families': 'Toplam Aile',
    'all_arrived': 'Hepsi Geldi',
    'partial': 'Kısmi',
    'scattered': 'Dağınık',
    'members_arrived': 'Üye Geldi',
    'all_together': 'Hep Birlikte',
    'separated': 'Ayrılmış',
    'incomplete': 'Eksik',
    'mother': 'Anne',
    'father': 'Baba',
    'child': 'Çocuk',
    'individual': 'Birey',
    'spouse': 'Eş',
    'other': 'Diğer',
    'independent_record': 'Bireysel Kayıt',
    'owner': 'Sorumlu',
    'member': 'Üye',
    'family_suffix': ' Ailesi',
    'status_inside': 'İçeride',
    'status_outside': 'Dışarıda',
    'member_count': 'Üye',
    'family_status_complete': 'Tam',
    'family_status_separated': 'Ayrı',
    'family_status_incomplete': 'Eksik',

    // Unregistered
    'unregistered_management': 'Kayıtsız Kişi Yönetimi',
    'unregistered_desc': 'Kayıtsız gelen kişileri sisteme ekleyin',
    'add_record': 'Yeni Kayıt Ekle',
    'select_shelter': 'Sığınak Seçin',
    'people_count_label': 'Kişi Sayısı',
    'enter_people_count': 'Kişi sayısını girin',
    'optional_notes': 'Opsiyonel notlar...',
    'notes': 'Notlar',
    'save': 'Kaydet',
    'cancel': 'İptal',
    'recent_entries': 'Son Kayıtlar',

    // Resources
    'resource_management': 'Kaynak Yönetimi',
    'resource_desc': 'Sığınaklardaki kaynakları takip edin',
    'critical_shelters': 'Kritik Sığınaklar',
    'water': 'SU',
    'medicine': 'İLAÇ',
    'blankets': 'BATTANİYE',
    'food': 'YEMEK',
    'fuel': 'GAZ / YAKIT',
    'hygiene': 'HİJYEN SETİ',
    'sufficient': 'Yeterli',
    'depleted': 'Tükendi',
    'request': 'Gönder',
    'request_supply': 'Talep Et',
    'good': 'İyi',
    'critical': 'Kritik',
    'last_updated': 'Son Güncelleme',
    'calculation_standards': 'Operasyonel Hesaplama Standartları',
    'calculation_desc': 'Sistem, kaynak durumlarını aşağıdaki kişi başı standartlara göre otomatik hesaplar.',
    'water_consumption_label': 'Su Tüketimi',
    'food_consumption_label': 'Gıda Tüketimi',
    'fuel_consumption_label': 'Yakıt Tüketimi',
    'health_tracking_label': 'Sağlık Takibi',
    'shelter_standard_label': 'Barınma',
    'hygiene_standard_label': 'Hijyen',
    'water_standard_desc': 'Su miktarı kişi başına günlük tüketim standardına göre hesaplanır.',
    'food_standard_desc': 'Gıda ihtiyacı kişi başına günlük iki öğün standardına göre hesaplanır.',
    'fuel_standard_desc': 'Yakıt ihtiyacı sığınaktaki kişi sayısına göre tahmini olarak hesaplanır.',
    'health_standard_desc': 'Sağlık kaynakları gelen yardım taleplerine göre takip edilir.',
    'shelter_standard_desc': 'Battaniye ihtiyacı sığınaktaki kişi sayısına göre belirlenir.',
    'hygiene_standard_desc': 'Hijyen malzemesi ihtiyacı kişi sayısına göre hesaplanır.',
    'secondary_shelters': 'Yan Sığınaklar',
    'safe_spots': 'Güvenli Alanlar',
    'main_shelter_assoc': 'Bağlı Olduğu Ana Sığınak',
    'nearby_spots': 'Yakındaki Güvenli Noktalar',
    'spare': 'Yedek',
    'condition': 'Durum',
    'stock': 'Stok',
    'days_label': 'Gün',
    'request_sent_msg': 'Talep operasyon merkezine iletildi.',
    'calculation_logic': 'Hesaplama Mantığı',
    'logic_desc': 'Durum = Mevcut Stok / (Nüfus × Günlük Standart)',

    // Notifications
    'notification_management': 'Bildirim Yönetimi',
    'notification_desc': 'Kullanıcılara bildirim gönderin',
    'total_sent': 'Gönderilen',
    'today': 'Bugün',
    'recipients': 'Alıcılar',
    'send_notification': 'Yeni Bildirim Gönder',
    'notification_type': 'Bildirim Türü',
    'shelter_opened': 'Sığınak Açıldı',
    'shelter_closed': 'Sığınak Kapandı',
    'earthquake': 'Deprem',
    'instruction': 'Talimat',
    'title': 'Başlık',
    'message': 'Mesaj',
    'enter_title': 'Başlık girin',
    'enter_message': 'Mesaj girin',
    'region': 'Bölge',
    'target': 'Hedef',
    'send': 'GÖNDER',
    'recent_notifications': 'Son Bildirimler',
    'sent': 'Gönderildi',
    'donations': 'Bağış Yönetimi',
    'donations_desc': 'Tüm ayni ve nakdi yardımların takibi',
    'donation_management': 'Bağış Yönetimi',
    'donation_desc': 'Güncel bağış kayıtları ve istatistikler',
    'monetary': 'NAKDİ',
    'in_kind': 'AYNİ',
    'total_monetary_donation': 'TOPLAM NAKDİ BAĞIŞ',
    'total_resource_count': 'TOPLAM KAYNAK ADEDİ',
    'donor_count': 'BAĞIŞÇI SAYISI',
    'status_analysis': 'DURUM ANALİZİ',
    'donor': 'BAĞIŞÇI',
    'amount_content': 'MİKTAR / İÇERİK',
    'date': 'TARİH',
    'view_all_history': 'TÜM BAĞIŞ GEÇMİŞİNİ GÖRÜNTÜLE',
    'search_donor_placeholder': 'Bağışçı veya makbuz no ile ara...',
    'monthly': 'AYLIK',
    'one_time': 'TEK SEFER',
    'received': 'TESLİM ALINDI',
    'processing': 'İŞLENİYOR',

    // Common
    'logout': 'Çıkış',
    'settings': 'Ayarlar',
    'ago': 'önce',
    'min': 'dk',
    'hour': 'saat',
    'loading': 'Yükleniyor...',
    'waiting_for': 'dakikadır bekliyor',
    'in_progress_for': 'dakikadır işlemde',
    'completed_ago': 'dakika önce tamamlandı',
    'minutes': 'dakika',
    'loading_requests': 'Talepler yükleniyor...',
    'error_occurred': 'Bir hata oluştu',
    'no_location': 'Konum bilgisi yok',
    'id_label': 'ID',
    'save_changes': 'Değişiklikleri Kaydet',
    'brand_name': 'Shelter Smart',
    
    // Invite
    'invite_new_user': 'Yeni Kullanıcı Davet Et',
    'invite_superadmin_panel': 'YALNIZCA SÜPER ADMİN PANELİ',
    'user_role': 'KULLANICI ROLÜ',
    'send_invitation': 'DAVETİYE GÖNDER',
    'invitation_sent_success': 'Davetiye başarıyla gönderildi!',
    'invitation_failed': 'Davetiye gönderilemedi.',
    'invite_link': 'DAVET BAĞLANTISI',
    'super_admin_label': 'Üst Yönetici',
    'invite_desc': 'Sisteme yeni ADMİN veya STAFF davet edin.',
    'role_permissions': 'ROL YETKİLERİ',
    'admin_full_access': 'Tam Erişim Yetkisi',
    'staff_field_access': 'Saha Operasyon Yetkisi',

    // Comments
    'comments_management': 'Yorum Yönetimi',
    'comments_desc': 'Kullanıcı deneyimleri ve geri bildirimler',
    'average_rating': 'ORTALAMA PUAN',
    'total_comments': 'TOPLAM YORUM',
    'response_rate': 'YANIT ORANI',
    'search_comments': 'Yorumlarda ara...',
    'recent_feedback': 'SON GELEN YORUMLAR',
    'no_comments_found': 'Yorum Bulunamadı',
    'search_no_results': 'Arama sonuç vermedi.',
    'load_more': 'DAHA FAZLA',
    'loading_feedback': 'Geri bildirimler yükleniyor...',
    'unknown_shelter': 'Bilinmeyen Sığınak',
    'misafir_kullanici': 'Misafir Kullanıcı',
    'genel_merkez': 'Genel Merkez',
    'toplam_bagis_miktari': 'Toplam Bağış Miktarı',
    'toplam_kayitli_birim': 'Toplam Kayıtlı Birim',
    'toplam_islem_adedi': 'Toplam İşlem Adedi',
    'adet': 'Adet',
    'dashboard_desc': 'Sistem modülleri ve yönetim araçları.',
    'shelters_title': 'Sığınaklar',
    'shelters_dashboard_desc': 'Sistemdeki tüm sığınakların anlık doluluk oranlarını, kapasite durumlarını ve operasyonel verimliliklerini tek bir ekrandan yönetin.',
    'qr_logs_title': 'QR Kayıtları',
    'qr_logs_dashboard_desc': 'Güvenli bölgelere yapılan tüm QR tabanlı giriş ve çıkış trafik loglarını anlık olarak izleyin ve geçmişini detaylıca analiz edin.',
    'emergency_title': 'Acil Durum',
    'emergency_dashboard_desc': 'Bölgeden gelen acil durum sinyallerini izleyin, kriz anlarında saniyeler içinde doğru yönlendirmeler yaparak anında müdahale sağlayın.',
    'unregistered_title': 'Kayıtsız Kişiler',
    'unregistered_dashboard_desc': 'Sisteme henüz kaydedilmemiş, kimliği belirsiz veya geçici olarak sığınakta bulunan kişileri takip edip yönetin.',
    'families_title': 'Aile Paneli',
    'families_dashboard_desc': 'Sisteme kayıtlı tüm ailelerin ve bağımsız bireylerin demografik bilgilerini, özel ihtiyaçlarını ve konumlarını merkezi olarak takip edin.',
    'donations_title': 'Bağışlar',
    'donations_dashboard_desc': 'Kuruma sağlanan tüm ayni ve nakdi yardımların geliş süreçlerini, onay mekanizmalarını ve şeffaf kayıtlarını detaylı bir şekilde denetleyin.',
    'resources_title': 'Kaynaklar',
    'resources_dashboard_desc': 'Sahadaki kritik lojistik kaynakları, temel ihtiyaç stoklarını ve envanter tüketimini anlık verilerle izleyerek tedarik zincirini optimize edin.',
    'invite_title': 'Yeni Kullanıcı',
    'invite_dashboard_desc': 'Sisteme yeni bir yönetici veya personeli güvenli bir şekilde davet ederek ekip yetkilendirmesini yönetin.',
  },
  en: {
    // Login
    'admin_panel': 'Admin Panel',
    'shelter_system': 'Shelter Management System',
    'account_type': 'Account Type',
    'admin': 'Admin',
    'staff': 'Staff',
    'username': 'Username',
    'password': 'Password',
    'login': 'Login',
    'demo_note': 'Demo: admin/123456 or staff/123456',
    'invalid_credentials': 'Invalid credentials',
    'email_address': 'Email Address',
    'register': 'Register',

    // Dashboard
    'dashboard': 'Dashboard',
    'welcome': 'Welcome',
    'central_admin': 'Central Administrator',
    'shelter_staff': 'Shelter Staff',
    'total_people': 'Total People',
    'total_shelters': 'Total Shelters',
    'emergency_requests': 'Emergency Requests',
    'capacity_usage': 'Capacity Usage',
    'emergency_summary': 'Emergency Summary',
    'shelters_status': 'Shelters Status',
    'main_shelter': 'Main Shelter',
    'main_shelters': 'Main Shelters',
    'current_shelter': 'Current Shelter',
    'small_shelter': 'Small Shelter',
    'open': 'Open',
    'closed': 'Closed',
    'full': 'Full',
    'quick_actions': 'Quick Actions',
    'view_all_shelters': 'View All Shelters',
    'emergency_alerts': 'Emergency Alerts',
    'manage_capacity': 'Manage Capacity',
    'send_notification_btn': 'Send Notification',
    'staff_dashboard': 'Field Operations Screen',
    'admin_dashboard': 'Regional Management Panel',
    'super_admin_dashboard': 'Strategic Command Center',
    'seismic_heartbeat': 'Seismic Heartbeat',
    'live_data': 'Live Data Streaming',
    'operational_readiness': 'Operational Readiness',
    'team_directory': 'Team Directory',
    'active_staff': 'Active Field Staff',
    'administrators': 'Administrators',
    'my_team': 'My Team',
    'on_duty': 'On Duty',
    'on_break': 'On Break',
    'contact_admin': 'Contact Admin',
    'staff_performance': 'Staff Performance',
    'earthquake_monitor': 'Live Earthquake Monitor',
    'latest_earthquakes': 'Latest Earthquakes',
    'magnitude': 'Magnitude',
    'depth': 'Depth',
    'location_city': 'Location / City',
    'istanbul_status': 'Istanbul Status',
    'safe_zone_status': 'Safe Zone Analysis',
    'last_activity': 'Last Activity',

    // Shelters
    'shelter_management': 'Shelter Management',
    'manage_shelters_desc': 'Manage all shelters in the system',
    'add_shelter': 'Add Shelter',
    'add_shelter_desc': 'Fill in the details below to add a new shelter.',
    'shelter_name': 'Shelter Name',
    'location': 'Location',
    'type': 'Type',
    'status': 'Status',
    'capacity': 'Capacity',
    'actions': 'Actions',
    'main': 'Main',
    'small': 'Small',
    'linked_to': 'Linked to',
    'address': 'Address',
    'latitude': 'Latitude',
    'longitude': 'Longitude',

    // Capacity
    'capacity_management': 'Capacity Management',
    'capacity_desc': 'Shelter sections and capacities',
    'total_capacity': 'Total Capacity',
    'occupied': 'Occupied',
    'available': 'Available',
    'usage': 'Usage',
    'overall_occupancy': 'Overall Occupancy',
    'auto_update_qr': 'Auto-updated via QR scanning',
    'sections': 'Sections',
    'families': 'Families',
    'individuals': 'Individuals',
    'children': 'Children',
    'special_needs': 'Special Needs',
    'unregistered': 'Unregistered',
    'current': 'Current',
    'max': 'Maximum',
    'update': 'Update',

    // Emergency
    'emergency_management': 'Emergency Requests',
    'emergency_desc': 'Manage all emergency calls',
    'all': 'All',
    'new': 'New',
    'in_progress': 'In Progress',
    'completed': 'Completed',
    'resolved': 'Resolved',
    'sos': 'SOS',
    'ambulance': 'Ambulance',
    'transfer': 'Transfer',
    'high_priority': 'High Priority',
    'high': 'High',
    'medium': 'Medium',
    'low': 'Low',
    'call': 'Call',
    'navigate': 'Navigate',
    'start': 'Start',
    'complete': 'Complete',

    // QR Logs
    'qr_logs': 'QR Entry/Exit Logs',
    'qr_logs_desc': 'Track all QR scan records',
    'entry': 'Entry',
    'exit': 'Exit',
    'net_change': 'Net Change',
    'total_logs': 'Total Logs',
    'people_count': 'People Count',
    'time': 'Time',
    'user_label': 'User',
    'section_label': 'Section',
    'qr_code_label': 'QR Code',
    'all_shelters': 'All Shelters',

    // Families
    'family_management': 'Family Management',
    'family_desc': 'Keep families together',
    'total_families': 'Total Families',
    'all_arrived': 'All Arrived',
    'partial': 'Partial',
    'scattered': 'Scattered',
    'members_arrived': 'Members Arrived',
    'all_together': 'All Together',
    'separated': 'Separated',
    'incomplete': 'Incomplete',
    'mother': 'Mother',
    'father': 'Father',
    'child': 'Child',
    'individual': 'Individual',
    'spouse': 'Spouse',
    'other': 'Other',
    'independent_record': 'Independent Record',
    'owner': 'Owner',
    'member': 'Member',
    'family_suffix': ' Family',
    'status_inside': 'Inside',
    'status_outside': 'Outside',
    'member_count': 'Member',
    'family_status_complete': 'Complete',
    'family_status_separated': 'Separated',
    'family_status_incomplete': 'Incomplete',

    // Unregistered
    'unregistered_management': 'Unregistered Management',
    'unregistered_desc': 'Add unregistered people to the system',
    'add_record': 'Add New Record',
    'select_shelter': 'Select Shelter',
    'people_count_label': 'People Count',
    'enter_people_count': 'Enter number of people',
    'optional_notes': 'Optional notes...',
    'notes': 'Notes',
    'save': 'Save',
    'cancel': 'Cancel',
    'recent_entries': 'Recent Entries',

    // Resources
    'resource_management': 'Resource Management',
    'resource_desc': 'Track shelter resources',
    'critical_shelters': 'Critical Shelters',
    'water': 'Water',
    'medicine': 'Medicine',
    'blankets': 'Blankets',
    'food': 'Food',
    'sufficient': 'Sufficient',
    'depleted': 'Depleted',
    'request': 'Request',
    'request_supply': 'Request Supply',
    'good': 'Good',
    'critical': 'Critical',
    'last_updated': 'Last Updated',
    'calculation_standards': 'Operational Calculation Standards',
    'calculation_desc': 'System automatically calculates resource statuses based on per-person standards below.',
    'water_consumption_label': 'Water Consumption',
    'food_consumption_label': 'Food Consumption',
    'fuel_consumption_label': 'Fuel Consumption',
    'health_tracking_label': 'Health Tracking',
    'shelter_standard_label': 'Shelter',
    'hygiene_standard_label': 'Hygiene',
    'water_standard_desc': 'Shows average daily water need per person. (3 L / Person / Day)',
    'food_standard_desc': 'Shows daily food distributed per person in the shelter. (2 Meals / Person)',
    'fuel_standard_desc': 'Shows average daily fuel consumption for cooking and heating.',
    'health_standard_desc': 'Shows tracking of health cases in the shelter through the system.',
    'shelter_standard_desc': 'Shows the amount of blankets allocated for each person. (1 Blanket / Person)',
    'hygiene_standard_desc': 'Shows the usage period of the hygiene kit distributed per person. (1 Set / 3 Days / Person)',
    'secondary_shelters': 'Secondary Shelters',
    'safe_spots': 'Safe Spots',
    'main_shelter_assoc': 'Associated Main Shelter',
    'nearby_spots': 'Nearby Safe Points',
    'spare': 'Reserve',
    'condition': 'Status',
    'stock': 'Stock',
    'days_label': 'Days',
    'request_sent_msg': 'Request sent to operations center.',
    'calculation_logic': 'Calculation Logic',
    'logic_desc': 'Status = Current Stock / (Population × Daily Standard)',

    // Notifications
    'notification_management': 'Notification Management',
    'notification_desc': 'Send notifications to users',
    'total_sent': 'Total Sent',
    'today': 'Today',
    'recipients': 'Recipients',
    'send_notification': 'Send New Notification',
    'notification_type': 'Notification Type',
    'shelter_opened': 'Shelter Opened',
    'shelter_closed': 'Shelter Closed',
    'earthquake': 'Earthquake',
    'instruction': 'Instruction',
    'title': 'Title',
    'message': 'Message',
    'enter_title': 'Enter title',
    'enter_message': 'Enter message',
    'region': 'Region',
    'target': 'Target',
    'send': 'Send',
    'recent_notifications': 'Recent Notifications',
    'sent': 'Sent',
    'donation_management': 'Donation Management',
    'donation_desc': 'Current donation records and statistics',
    'monetary': 'MONETARY',
    'in_kind': 'IN-KIND',
    'total_monetary_donation': 'TOTAL MONETARY DONATION',
    'total_resource_count': 'TOTAL RESOURCE COUNT',
    'donor_count': 'DONOR COUNT',
    'status_analysis': 'STATUS ANALYSIS',
    'donor': 'DONOR',
    'amount_content': 'AMOUNT / CONTENT',
    'date': 'DATE',
    'view_all_history': 'VIEW ALL DONATION HISTORY',
    'search_donor_placeholder': 'Search by donor or receipt no...',
    'monthly': 'MONTHLY',
    'one_time': 'ONE-TIME',
    'received': 'RECEIVED',
    'processing': 'PROCESSING',

    // Common
    'logout': 'Logout',
    'settings': 'Settings',
    'ago': 'ago',
    'min': 'min',
    'hour': 'hour',
    'loading': 'Loading...',
    'waiting_for': 'minutes waiting',
    'in_progress_for': 'minutes in progress',
    'completed_ago': 'minutes ago completed',
    'minutes': 'minutes',
    'loading_requests': 'Loading requests...',
    'error_occurred': 'An error occurred',
    'no_location': 'No location info available',
    'id_label': 'ID',
    'save_changes': 'Save Changes',
    'brand_name': 'Shelter Smart',

    // Invite
    'invite_new_user': 'Invite New User',
    'invite_superadmin_panel': 'SUPER ADMIN PANEL ONLY',
    'user_role': 'USER ROLE',
    'send_invitation': 'SEND INVITATION',
    'invitation_sent_success': 'Invitation sent successfully!',
    'invitation_failed': 'Failed to send invitation.',
    'invite_link': 'INVITATION LINK',
    'super_admin_label': 'Top Administrator',
    'invite_desc': 'Invite a new ADMIN or STAFF to the system.',
    'role_permissions': 'ROLE PERMISSIONS',
    'admin_full_access': 'Full Access Permission',
    'staff_field_access': 'Field Operation Permission',
    'unknown_shelter': 'Unknown Shelter',
    'misafir_kullanici': 'Guest User',
    'genel_merkez': 'General Center',
    'toplam_bagis_miktari': 'Total Donation Amount',
    'toplam_kayitli_birim': 'Total Registered Units',
    'toplam_islem_adedi': 'Total Transaction Count',
    'adet': 'Units',
    'dashboard_desc': 'System modules and management tools.',
    'shelters_title': 'Shelters',
    'shelters_dashboard_desc': 'Manage real-time occupancy rates, capacity status, and operational efficiency of all shelters in the system from a single screen.',
    'qr_logs_title': 'QR Logs',
    'qr_logs_dashboard_desc': 'Instantly monitor all QR-based entry and exit traffic logs to safe zones and analyze history in detail.',
    'emergency_title': 'Emergency',
    'emergency_dashboard_desc': 'Monitor emergency signals from the region, providing instant intervention by making the right guidance in seconds during crises.',
    'unregistered_title': 'Unregistered People',
    'unregistered_dashboard_desc': 'Track and manage people who have not yet been registered in the system, unidentified, or temporarily in the shelter.',
    'families_title': 'Family Panel',
    'families_dashboard_desc': 'Centrally track demographic information, special needs, and locations of all registered families and independent individuals.',
    'donations_title': 'Donations',
    'donations_dashboard_desc': 'Audit all in-kind and monetary aid processes, approval mechanisms, and transparent records in detail.',
    'resources_title': 'Resources',
    'resources_dashboard_desc': 'Optimize the supply chain by monitoring critical logistical resources, basic need stocks, and inventory consumption in the field with real-time data.',
    'invite_title': 'New User',
    'invite_dashboard_desc': 'Manage team authorization by securely inviting a new admin or staff member to the system.',
  },
  ar: {
    // Login
    'admin_panel': 'لوحة الإدارة',
    'shelter_system': 'نظام إدارة الملاجئ',
    'account_type': 'نوع الحساب',
    'admin': 'مدير',
    'staff': 'موظف',
    'username': 'اسم المستخدم',
    'password': 'كلمة المرور',
    'login': 'تسجيل الدخول',
    'demo_note': 'تجريبي: admin/123456 أو staff/123456',
    'invalid_credentials': 'بيانات الاعتماد غير صالحة',
    'email_address': 'البريد الإلكتروني',
    'register': 'تسجيل',

    // Dashboard
    'dashboard': 'لوحة التحكم',
    'welcome': 'مرحباً',
    'central_admin': 'مدير مركزي',
    'shelter_staff': 'موظف ملجأ',
    'total_people': 'إجمالي الأشخاص',
    'total_shelters': 'إجمالي الملاجئ',
    'emergency_requests': 'طلبات الطوارئ',
    'capacity_usage': 'استخدام السعة',
    'emergency_summary': 'ملخص الطوارئ',
    'shelters_status': 'حالة الملاجئ',
    'main_shelter': 'ملجأ رئيسي',
    'main_shelters': 'الملاجئ الرئيسية',
    'current_shelter': 'الملجأ الحالي',
    'small_shelter': 'ملجأ صغير',
    'open': 'مفتوح',
    'closed': 'مغلق',
    'full': 'ممتلئ',
    'quick_actions': 'إجراءات سريعة',
    'view_all_shelters': 'مشاهدة جميع الملاجئ',
    'emergency_alerts': 'تنبيهات الطوارئ',
    'manage_capacity': 'إدارة السعة',
    'send_notification_btn': 'إرسال إشعار',
    'staff_dashboard': 'شاشة العمليات الميدانية',
    'admin_dashboard': 'لوحة الإدارة الإقليمية',
    'super_admin_dashboard': 'مركز القيادة الاستراتيجي',
    'seismic_heartbeat': 'نبضات القلب الزلزالية',
    'live_data': 'بث البيانات الحية',
    'operational_readiness': 'الاستعداد العملياتي',
    'team_directory': 'دليل الفريق',
    'active_staff': 'الموظفون الميدانيون النشطون',
    'administrators': 'المديرون',
    'my_team': 'فريقي',
    'on_duty': 'في الخدمة',
    'on_break': 'في استراحة',
    'contact_admin': 'اتصل بالمدير',
    'staff_performance': 'أداء الموظفين',
    'earthquake_monitor': 'مراقبة الزلازل الحية',
    'latest_earthquakes': 'أحدث الزلازل',
    'magnitude': 'القوة',
    'depth': 'العمق',
    'location_city': 'الموقع / المدينة',
    'istanbul_status': 'حالة اسطنبول',
    'safe_zone_status': 'تحليل المنطقة الآمنة',
    'last_activity': 'النشاط الأخير',

    // Shelters
    'shelter_management': 'إدارة الملاجئ',
    'manage_shelters_desc': 'إدارة جميع الملاجئ في النظام',
    'add_shelter': 'إضافة ملجأ',
    'add_shelter_desc': 'يرجى ملء التفاصيل أدناه لإضافة ملجأ جديد.',
    'shelter_name': 'اسم الملجأ',
    'location': 'الموقع',
    'type': 'النوع',
    'status': 'الحالة',
    'capacity': 'السعة',
    'actions': 'الإجراءات',
    'main': 'رئيسي',
    'small': 'صغير',
    'linked_to': 'مرتبط بـ',
    'address': 'العنوان',
    'latitude': 'خط العرض',
    'longitude': 'خط الطول',

    // Capacity
    'capacity_management': 'إدارة السعة',
    'capacity_desc': 'أقسام الملجأ والسعات',
    'total_capacity': 'السعة الإجمالية',
    'occupied': 'مشغول',
    'available': 'متاح',
    'usage': 'الاستخدام',
    'overall_occupancy': 'الإشغال الإجمالي',
    'auto_update_qr': 'يتم التحديث تلقائياً عبر مسح QR',
    'sections': 'الأقسام',
    'families': 'عائلات',
    'individuals': 'أفراد',
    'children': 'أطفال',
    'special_needs': 'احتياجات خاصة',
    'unregistered': 'غير مسجلين',
    'current': 'الحالي',
    'max': 'الأقصى',
    'update': 'تحديث',

    // Emergency
    'emergency_management': 'طلبات الطوارئ',
    'emergency_desc': 'إدارة جميع مكالمات الطوارئ',
    'all': 'الكل',
    'new': 'جديد',
    'in_progress': 'قيد التنفيذ',
    'completed': 'مكتمل',
    'resolved': 'محلول',
    'sos': 'SOS',
    'ambulance': 'إسعاف',
    'transfer': 'نقل',
    'high_priority': 'أولوية عالية',
    'high': 'عالي',
    'medium': 'متوسط',
    'low': 'منخفض',
    'call': 'اتصال',
    'navigate': 'التنقل',
    'start': 'بدء',
    'complete': 'إنهاء',

    // QR Logs
    'qr_logs': 'سجلات الدخول/الخروج QR',
    'qr_logs_desc': 'تتبع جميع سجلات مسح QR',
    'entry': 'دخول',
    'exit': 'خروج',
    'net_change': 'التغيير الصافي',
    'total_logs': 'إجمالي السجلات',
    'people_count': 'عدد الأشخاص',
    'time': 'الوقت',
    'user_label': 'المستخدم',
    'section_label': 'القسم',
    'qr_code_label': 'كود QR',
    'all_shelters': 'جميع الملاجئ',

    // Families
    'family_management': 'إدارة العائلات',
    'family_desc': 'إبقاء العائلات معاً',
    'total_families': 'إجمالي العائلات',
    'all_arrived': 'وصل الجميع',
    'partial': 'جزئي',
    'scattered': 'متفرقون',
    'members_arrived': 'أفراد وصلوا',
    'all_together': 'معاً',
    'separated': 'منفصلون',
    'incomplete': 'غير مكتمل',
    'mother': 'الأم',
    'father': 'الأب',
    'child': 'الطفل',
    'individual': 'فرد',
    'spouse': 'الشريك',
    'other': 'أخرى',
    'independent_record': 'سجل فردي',
    'owner': 'مسؤول',
    'member': 'عضو',
    'family_suffix': ' عائلة ',
    'status_inside': 'في الداخل',
    'status_outside': 'في الخارج',
    'member_count': 'عضو',
    'family_status_complete': 'كامل',
    'family_status_separated': 'منفصل',
    'family_status_incomplete': 'ناقص',

    // Unregistered
    'unregistered_management': 'إدارة غير المسجلين',
    'unregistered_desc': 'إضافة الأشخاص غير المسجلين للنظام',
    'add_record': 'إضافة سجل جديد',
    'select_shelter': 'اختر الملجأ',
    'people_count_label': 'عدد الأشخاص',
    'enter_people_count': 'أدخل عدد الأشخاص',
    'optional_notes': 'ملاحظات اختيارية...',
    'notes': 'ملاحظات',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'recent_entries': 'الإدخالات الأخيرة',

    // Resources
    'resource_management': 'إدارة الموارد',
    'resource_desc': 'تتبع موارد الملاجئ',
    'critical_shelters': 'ملاجئ حرجة',
    'water': 'ماء',
    'medicine': 'دواء',
    'blankets': 'بطانيات',
    'food': 'طعام',
    'sufficient': 'كافي',
    'depleted': 'نفد',
    'request': 'طلب',
    'request_supply': 'طلب توريد',
    'good': 'جيد',
    'critical': 'حرج',

    // Notifications
    'notification_management': 'إدارة الإشعارات',
    'notification_desc': 'إرسال إشعارات للمستخدمين',
    'total_sent': 'إجمالي المُرسل',
    'today': 'اليوم',
    'recipients': 'المستلمون',
    'send_notification': 'إرسال إشعار جديد',
    'notification_type': 'نوع الإشعار',
    'shelter_opened': 'فتح ملجأ',
    'shelter_closed': 'إغلاق ملجأ',
    'earthquake': 'زلزال',
    'instruction': 'تعليمات',
    'title': 'العنوان',
    'message': 'الرسالة',
    'enter_title': 'أدخل العنوان',
    'enter_message': 'أدخل الرسالة',
    'region': 'المنطقة',
    'target': 'الهدف',
    'send': 'إرسال',
    'recent_notifications': 'الإشعارات الأخيرة',
    'sent': 'تم الإرسال',
    'donation_management': 'إدارة التبرعات',
    'donation_desc': 'سجلات التبرعات والإحصائيات الحالية',
    'monetary': 'نقدي',
    'in_kind': 'عيني',
    'total_monetary_donation': 'إجمالي التبرعات النقدية',
    'total_resource_count': 'إجمالي عدد الموارد',
    'donor_count': 'عدد المتبرعين',
    'status_analysis': 'تحليل الحالة',
    'donor': 'متبرع',
    'amount_content': 'المبلغ / المحتوى',
    'date': 'التاريخ',
    'view_all_history': 'عرض سجل التبرعات بالكامل',
    'search_donor_placeholder': 'البحث عن طريق المتبرع أو رقم الإيصال...',
    'monthly': 'شهري',
    'one_time': 'مرة واحدة',
    'received': 'تم الاستلام',
    'processing': 'قيد المعالجة',

    // Common
    'logout': 'تسجيل خروج',
    'settings': 'الإعدادات',
    'ago': 'منذ',
    'min': 'دقيقة',
    'hour': 'ساعة',
    'loading': 'جارٍ التحميل...',
    'waiting_for': 'دقائق بانتظار',
    'in_progress_for': 'دقائق قيد التنفيذ',
    'completed_ago': 'دقائق منذ اكتمالها',
    'minutes': 'دقائق',
    'loading_requests': 'جارٍ تحميل الطلبات...',
    'error_occurred': 'حدث خطأ',
    'no_location': 'لا توجد معلومات عن الموقع',
    'id_label': 'المعرف',
    'save_changes': 'حفظ التغييرات',
    'brand_name': 'Shelter Smart',

    // Invite
    'invite_new_user': 'دعوة مستخدم جديد',
    'invite_superadmin_panel': 'لوحة السوبر أدمن فقط',
    'user_role': 'دور المستخدم',
    'send_invitation': 'إرسال دعوة',
    'invitation_sent_success': 'تم إرسال الدعوة بنجاح!',
    'invitation_failed': 'فشل إرسال الدعوة.',
    'invite_link': 'رابط الدعوة',
    'super_admin_label': 'مدير أعلى',
    'invite_desc': 'دعوة مسؤول جديد (ADMIN) أو موظف (STAFF) إلى النظام.',
    'role_permissions': 'صلاحيات الأدوار',
    'admin_full_access': 'صلاحية الوصول الكامل',
    'staff_field_access': 'صلاحية العمليات الميدانية',
    'unknown_shelter': 'ملجأ غير معروف',
    'misafir_kullanici': 'مستخدم زائر',
    'genel_merkez': 'المركز العام',
    'toplam_bagis_miktari': 'إجمالي مبلغ التبرع',
    'toplam_kayitli_birim': 'إجمالي الوحدات المسجلة',
    'toplam_islem_adedi': 'إجمالي عدد العمليات',
    'adet': 'وحدات',
    'dashboard_desc': 'وحدات النظام وأدوات الإدارة.',
    'shelters_title': 'الملاجئ',
    'shelters_dashboard_desc': 'إدارة معدلات الإشغال الفوري وحالات السعة والكفاءة التشغيلية لجميع الملاجئ في النظام من شاشة واحدة.',
    'qr_logs_title': 'سجلات QR',
    'qr_logs_dashboard_desc': 'مراقبة جميع سجلات حركة الدخول والخروج المستندة إلى QR في المناطق الآمنة فورياً وتحليل تاريخها بالتفصيل.',
    'emergency_title': 'حالة الطوارئ',
    'emergency_dashboard_desc': 'مراقبة إشارات الطوارئ القادمة من المنطقة، وتقديم تدخل فوري من خلال التوجيه الصحيح في ثوانٍ خلال الأزمات.',
    'unregistered_title': 'أشخاص غير مسجلين',
    'unregistered_dashboard_desc': 'تتبع وإدارة الأشخاص الذين لم يتم تسجيلهم بعد في النظام، أو غير المحددين، أو الموجودين في الملجأ مؤقتاً.',
    'families_title': 'لوحة العائلات',
    'families_dashboard_desc': 'تتبع المعلومات الديموغرافية والاحتياجات الخاصة ومواقع جميع العائلات والأفراد المستقلين المسجلين في النظام مركزياً.',
    'donations_title': 'التبرعات',
    'donations_dashboard_desc': 'تدقيق جميع عمليات المساعدات النقدية والعينية المقدمة للمؤسسة وآليات الموافقة وسجلاتها الشفافة بالتفصيل.',
    'resources_title': 'الموارد',
    'resources_dashboard_desc': 'تحسين سلسلة التوريد من خلال مراقبة الموارد اللوجستية الحرجة واحتياطيات الاحتياجات الأساسية واستهلاك المخزون في الميدان ببيانات فورية.',
    'invite_title': 'مستخدم جديد',
    'invite_dashboard_desc': 'إدارة تفويض الفريق عن طريق دعوة مدير أو موظف جديد إلى النظام بأمان.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('tr');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      <div dir={isRTL ? 'rtl' : 'ltr'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
